[package]
name = "newbot"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iliana@buttslol.net>"]
edition = "2018"
license = "GPL-3.0-or-later"
publish = false
default-run = "newbot"

[profile.release]
lto = true
debug = 1

[dependencies]
dotenv = "0.15"
elefren = { version = "0.20", default-features = false, features = ["rustls-tls"] }
envy = "0.4"
failure = "0.1"
lambda_runtime = "0.2"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
unic-emoji-char = "0.9"

[patch.crates-io]
elefren = { git = "https://github.com/pwoolcoc/elefren.git" }
