[package]
name = "newbot"
version = "0.1.0"
authors = ["iliana destroyer of worlds <iliana@buttslol.net>"]
edition = "2018"
license = "GPL-3.0-or-later"
publish = false
default-run = "newbot"

[dependencies]
dotenv = "0.15"
elefren = { version = "0.20", optional = true, default-features = false, features = ["rustls-tls"] }
failure = "0.1"
minreq = { version = "2.0.0", features = ["https", "json-using-serde"] }
rand = "0.7"
serde = { version = "1", features = ["derive"] }
unic-emoji-char = { version = "0.9", optional = true }

[patch.crates-io]
elefren = { git = "https://github.com/pwoolcoc/elefren.git" }

[features]
default = ["elefren", "unic-emoji-char"]

[profile.release]
lto = true
debug = 1

[[bin]]
name = "classify-twemoji"
path = "src/bin/classify-twemoji.rs"
required-features = ["unic-emoji-char"]

[[bin]]
name = "newbot-setup"
path = "src/bin/setup.rs"
required-features = ["elefren"]
