name: CI
on:
  pull_request:
    branches: [🤖]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install -y musl-tools
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --locked --target x86_64-unknown-linux-musl --verbose
