name: Test
on:
  pull_request:
    branches: [🤖]
  push:
    branches: [try]
env:
  RUST_BACKTRACE: full
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup update stable
      - run: cargo fmt -- --check
      - run: cargo clippy --locked
      - run: cargo test --locked
